import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout, { SUB_TITLE } from './components/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>{ SUB_TITLE }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/posts/first-post">POST</Link>
      <div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div><div>=======</div>
    </Layout>
  )
}
