import { useState, useEffect } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from '../components/Layout'
import ThemeToogle from '../components/ThemeToggle'
import useWindowOffset from '../@hooks/useWindowOffset';

export default function Home() {
  const { top } = useWindowOffset();
  return (
    <Layout>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/posts/first-post">POST</Link>
      <ThemeToogle />
      <div style={{height: '2000px'}}>{top}</div>
    </Layout>
  )
}
